### ISSUE TITLE
Error: Cannot find module '../config/env'

### ISSUE THREAD

**Issue by xyy7260** [cc616/cra-demo#1]
我使用你搭建好的框架，然后自己配置了一些东西出现 
Error: Cannot find module '../config/env'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Volumes/web/webPc/JY/cra-demo-master/scripts/start.js:15:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by xyy7260** [comment]
这是我的package.json
"dependencies": {
    "antd": "^3.6.4",
    "axios": "^0.18.0",
    "autoprefixer": "7.1.6",
    "babel-core": "6.26.0",
    "babel-eslint": "8.2.3",
    "babel-jest": "20.0.3",
    "babel-loader": "7.1.2",
    "babel-plugin-import": "^1.8.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-preset-flow": "^6.23.0",
    "babel-preset-react-app": "^3.1.1",
    "babel-runtime": "6.26.0",
    "case-sensitive-paths-webpack-plugin": "2.1.1",
    "chalk": "1.1.3",
    "css-loader": "0.28.7",
    "dotenv": "4.0.0",
    "dotenv-expand": "4.2.0",
    "eslint": "4.19.1",
    "eslint-config-airbnb": "16.1.0",
    "eslint-config-react-app": "^2.1.0",
    "eslint-loader": "2.0.0",
    "eslint-plugin-flowtype": "2.46.2",
    "eslint-plugin-import": "2.11.0",
    "eslint-plugin-jsx-a11y": "6.0.3",
    "eslint-plugin-react": "7.7.0",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "1.1.5",
    "flow-bin": "^0.80.0",
    "fs-extra": "3.0.1",
    "html-webpack-plugin": "2.29.0",
    "husky": "^0.14.3",
    "jest": "20.0.4",
    "less": "2.7.2",
    "less-loader": "^4.1.0",
    "lint-staged": "^7.2.0",
    "mobx": "^5.0.3",
    "mobx-react": "^5.2.3",
    "mobx-react-devtools": "^5.0.1",
    "node-sass": "^4.9.0",
    "nprogress": "0.2.0",
    "object-assign": "4.1.1",
    "postcss-flexbugs-fixes": "3.2.0",
    "postcss-loader": "2.0.8",
    "promise": "8.0.1",
    "raf": "3.4.0",
    "react": "^16.4.1",
    "react-dev-utils": "^5.0.1",
    "react-dom": "^16.4.1",
    "react-loadable": "^5.5.0",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "resolve": "1.6.0",
    "resolve-url-loader": "^2.3.0",
    "sass-loader": "^7.0.3",
    "style-loader": "0.19.0",
    "sw-precache-webpack-plugin": "0.11.4",
    "url-loader": "0.6.2",
    "webpack": "3.8.1",
    "webpack-dev-server": "2.9.4",
    "webpack-manifest-plugin": "1.3.2",
    "whatwg-fetch": "2.0.3"
  },

**Comment by xyy7260** [comment]
粗心把那个删除了 不好意思

**Comment by cc616** [comment]
没事，有问题可以一起学习讨论，谢谢支持
