### ISSUE TITLE
在mobx打包发布，貌似需要自己配置

### ISSUE THREAD

**Issue by xyy7260** [cc616/cra-demo#2]
最近打包上线，貌似还没处理mobx对不lz

**Comment by cc616** [comment]
@xyy7260 
能具体描述问题吗？是build不成功还是啥？

**Comment by xyy7260** [comment]
@cc616  是这样，我打包过后，在ie浏览器包mobx的错误 ，感觉自己还需要配置是不是呢

**Comment by cc616** [comment]
@xyy7260 尴尬，按理说应该不需要配置，我自己也打包跑过，没有用IE已经很久了（捂脸），你打包后是用什么启动build文件的，node还是anywhere？还是其他的

**Comment by xyy7260** [comment]
@cc616 ×Error: [mobx] MobX 5+ requires Proxy and Symbol objects. If your environment doesn't support Proxy objects, please downgrade to MobX 4. For React Native Android, consider upgrading  降低？

**Comment by cc616** [comment]
@xyy7260 
MobX >=5 runs on any browser with ES6 proxy support. It will throw an error on startup on older environments such as IE11, Node.js <6 or React Native Android on old JavaScriptCore how-to-upgrade.
MobX 4 runs on any ES5 browser and will be actively maintained. The MobX 4 and 5 api's are the same and semantically can achieve the same, but MobX 4 has some limitations.
你可以看看你的IE版本，或者尝试安装mobx4

**Comment by xyy7260** [comment]
@cc616   
"mobx": "^5.0.3",
    "mobx-react": "^5.2.3",
    "mobx-react-devtools": "^5.0.1",
全部改成4.0.0？
