### ISSUE TITLE
CSS加载比js慢

### ISSUE THREAD

**Issue by xyy7260** [cc616/cra-demo#4]
你好，
发现webpack配置的css在加载过程中比js慢，以及打包过后引入的顺序也比js落后， 导致页面刷新时候css排版出现问题。
![image](https://user-images.githubusercontent.com/23183393/56419315-5fb41a80-62cc-11e9-842c-206c5ae3b809.png)

**Comment by cc616** [comment]
@xyy7260 你可以更改webpack的配置
