### ISSUE TITLE
你好怎么切换成https呢？

### ISSUE THREAD

**Issue by xyy7260** [cc616/cra-demo#5]
我看了一些配置，我直接把https ： true 但是 无法打开难道全局变量哪里做了什么处理呢？
谢谢

**Comment by cc616** [comment]
@xyy7260 不太明白你的问题，你是想部署的时候可以用https访问还是本地开发也要用https访问，还是获取其他service是用https代理

**Comment by xyy7260** [comment]
@cc616  就是开发时候使用https来访问

**Comment by xyy7260** [comment]
@cc616   我的是react-mobx 这一套

**Comment by cc616** [comment]
@xyy7260 这是很早的版本了，如果你要支持https你可以升级create-react-app的版本
![image](https://user-images.githubusercontent.com/9332135/57275419-1b4cbb00-70d1-11e9-81ed-9715195dea5a.png)

**Comment by cc616** [comment]
@xyy7260 新推了个分支react-mobx-https，不知道会不会影响你的业务，毕竟改了些配置，像脚手架都是不停的在升级，如果你需要支持新的特性就需要不停的跟着升级，所以还是建议自己掌握这些配置，目前这个不是最新的create-react-app； 这样使用HTTPS=true yarn start

**Comment by xyy7260** [comment]
@cc616  知道了感谢

**Comment by xyy7260** [comment]
@cc616   其实我还想有个问题想让你帮忙看看， 不知道你有没有多余的时间， 我目前3个项目都是在使用这个react-mobx开发的；
我的问题就是， 当页面加载的时候css执行顺序比JS慢，导致页面刷新或者跳转出现样式排版乱，
![52589FCE-3605-485C-8C5F-9175109BC9EE](https://user-images.githubusercontent.com/23183393/57348452-ae94f780-7188-11e9-82de-3750de8ad65b.png)
![78134EC7-F306-40E0-A206-277FC8ED72B5](https://user-images.githubusercontent.com/23183393/57348455-afc62480-7188-11e9-82f3-1283b0ecc594.png)
![9A804E7B-E943-46A1-9F84-68304B4A208B](https://user-images.githubusercontent.com/23183393/57348457-b2c11500-7188-11e9-91c7-d2c92b1e85e7.png)

我也尝试修改了 dev 和prod  配置还是不行 ，也不知道怎么让我的css 比JS 要先加载，所以 一直困扰这个问题 
感谢
